package xxrco.oracle.apps.pay.balanza.pop;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnioVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public AnioVOImpl() {
    }
}
