package xxrco.oracle.apps.pay.balanza.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxrco.oracle.apps.pay.balanza.schema.server.XxRcoPayAjuBzaProjEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxRcoPayAjuBzaProjVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int ANIO = 1;
    public static final int NUMEROMES = 2;
    public static final int MES = 3;
    public static final int GRUPONOMINA = 4;
    public static final int PROYECTO = 5;
    public static final int REGISTROPATRONAL = 6;
    public static final int CALCCUOTASSERINF = 7;
    public static final int CALCCUOTASSERRET = 8;
    public static final int CALCCUOTASSERSTA = 9;
    public static final int D002IMSS = 10;
    public static final int D002IMSSSTA = 11;
    public static final int CREATEDBY = 12;
    public static final int CREATIONDATE = 13;
    public static final int LASTUPDATEDBY = 14;
    public static final int LASTUPDATEDATE = 15;
    public static final int LASTUPDATELOGIN = 16;
    public static final int CUOTAPATRONAL = 17;

    /**This is the default constructor (do not remove)
     */
    public XxRcoPayAjuBzaProjVORowImpl() {
    }

    /**Gets XxRcoPayAjuBzaProjEO entity object.
     */
    public XxRcoPayAjuBzaProjEOImpl getXxRcoPayAjuBzaProjEO() {
        return (XxRcoPayAjuBzaProjEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for NUMERO_MES using the alias name NumeroMes
     */
    public Number getNumeroMes() {
        return (Number) getAttributeInternal(NUMEROMES);
    }

    /**Sets <code>value</code> as attribute value for NUMERO_MES using the alias name NumeroMes
     */
    public void setNumeroMes(Number value) {
        setAttributeInternal(NUMEROMES, value);
    }

    /**Gets the attribute value for MES using the alias name Mes
     */
    public String getMes() {
        return (String) getAttributeInternal(MES);
    }

    /**Sets <code>value</code> as attribute value for MES using the alias name Mes
     */
    public void setMes(String value) {
        setAttributeInternal(MES, value);
    }

    /**Gets the attribute value for GRUPO_NOMINA using the alias name GrupoNomina
     */
    public String getGrupoNomina() {
        return (String) getAttributeInternal(GRUPONOMINA);
    }

    /**Sets <code>value</code> as attribute value for GRUPO_NOMINA using the alias name GrupoNomina
     */
    public void setGrupoNomina(String value) {
        setAttributeInternal(GRUPONOMINA, value);
    }

    /**Gets the attribute value for PROYECTO using the alias name Proyecto
     */
    public String getProyecto() {
        return (String) getAttributeInternal(PROYECTO);
    }

    /**Sets <code>value</code> as attribute value for PROYECTO using the alias name Proyecto
     */
    public void setProyecto(String value) {
        setAttributeInternal(PROYECTO, value);
    }

    /**Gets the attribute value for REGISTRO_PATRONAL using the alias name RegistroPatronal
     */
    public String getRegistroPatronal() {
        return (String) getAttributeInternal(REGISTROPATRONAL);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_PATRONAL using the alias name RegistroPatronal
     */
    public void setRegistroPatronal(String value) {
        setAttributeInternal(REGISTROPATRONAL, value);
    }

    /**Gets the attribute value for CALC_CUOTA_SS_ER_INF using the alias name CalcCuotaSsErInf
     */
    public Number getCalcCuotaSsErInf() {
        return (Number) getAttributeInternal(CALCCUOTASSERINF);
    }

    /**Sets <code>value</code> as attribute value for CALC_CUOTA_SS_ER_INF using the alias name CalcCuotaSsErInf
     */
    public void setCalcCuotaSsErInf(Number value) {
        setAttributeInternal(CALCCUOTASSERINF, value);
    }

    /**Gets the attribute value for CALC_CUOTA_SS_ER_RET using the alias name CalcCuotaSsErRet
     */
    public Number getCalcCuotaSsErRet() {
        return (Number) getAttributeInternal(CALCCUOTASSERRET);
    }

    /**Sets <code>value</code> as attribute value for CALC_CUOTA_SS_ER_RET using the alias name CalcCuotaSsErRet
     */
    public void setCalcCuotaSsErRet(Number value) {
        setAttributeInternal(CALCCUOTASSERRET, value);
    }

    /**Gets the attribute value for CALC_CUOTA_SS_ER_STA using the alias name CalcCuotaSsErSta
     */
    public Number getCalcCuotaSsErSta() {
        return (Number) getAttributeInternal(CALCCUOTASSERSTA);
    }

    /**Sets <code>value</code> as attribute value for CALC_CUOTA_SS_ER_STA using the alias name CalcCuotaSsErSta
     */
    public void setCalcCuotaSsErSta(Number value) {
        setAttributeInternal(CALCCUOTASSERSTA, value);
    }

    /**Gets the attribute value for D002IMSS using the alias name D002imss
     */
    public Number getD002imss() {
        return (Number) getAttributeInternal(D002IMSS);
    }

    /**Sets <code>value</code> as attribute value for D002IMSS using the alias name D002imss
     */
    public void setD002imss(Number value) {
        setAttributeInternal(D002IMSS, value);
    }

    /**Gets the attribute value for D002IMSS_STA using the alias name D002imssSta
     */
    public Number getD002imssSta() {
        return (Number) getAttributeInternal(D002IMSSSTA);
    }

    /**Sets <code>value</code> as attribute value for D002IMSS_STA using the alias name D002imssSta
     */
    public void setD002imssSta(Number value) {
        setAttributeInternal(D002IMSSSTA, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ANIO:
            return getAnio();
        case NUMEROMES:
            return getNumeroMes();
        case MES:
            return getMes();
        case GRUPONOMINA:
            return getGrupoNomina();
        case PROYECTO:
            return getProyecto();
        case REGISTROPATRONAL:
            return getRegistroPatronal();
        case CALCCUOTASSERINF:
            return getCalcCuotaSsErInf();
        case CALCCUOTASSERRET:
            return getCalcCuotaSsErRet();
        case CALCCUOTASSERSTA:
            return getCalcCuotaSsErSta();
        case D002IMSS:
            return getD002imss();
        case D002IMSSSTA:
            return getD002imssSta();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CUOTAPATRONAL:
            return getCuotaPatronal();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case NUMEROMES:
            setNumeroMes((Number)value);
            return;
        case MES:
            setMes((String)value);
            return;
        case GRUPONOMINA:
            setGrupoNomina((String)value);
            return;
        case PROYECTO:
            setProyecto((String)value);
            return;
        case REGISTROPATRONAL:
            setRegistroPatronal((String)value);
            return;
        case CALCCUOTASSERINF:
            setCalcCuotaSsErInf((Number)value);
            return;
        case CALCCUOTASSERRET:
            setCalcCuotaSsErRet((Number)value);
            return;
        case CALCCUOTASSERSTA:
            setCalcCuotaSsErSta((Number)value);
            return;
        case D002IMSS:
            setD002imss((Number)value);
            return;
        case D002IMSSSTA:
            setD002imssSta((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CUOTAPATRONAL:
            setCuotaPatronal((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute CuotaPatronal
     */
    public Number getCuotaPatronal() {
        return (Number) getAttributeInternal(CUOTAPATRONAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CuotaPatronal
     */
    public void setCuotaPatronal(Number value) {
        setAttributeInternal(CUOTAPATRONAL, value);
    }
}
