package xxrco.oracle.apps.pay.balanza.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxrco.oracle.apps.pay.balanza.schema.server.XxRcoPayAjustesBalanzaEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxRcoPayjaustesBalanzaVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int ANIO = 1;
    public static final int NUMEROMES = 2;
    public static final int MES = 3;
    public static final int GRUPONOMINA = 4;
    public static final int AJUIMSSDEDUCIBLE = 5;
    public static final int AJUIMSSNODEDUCIBLE = 6;
    public static final int CANCFAPERIODOANTERIOR = 7;
    public static final int CANCFA = 8;
    public static final int CANCSYR = 9;
    public static final int CANCPROVPRIMVAC = 10;
    public static final int CANCPROVAGUINALDO = 11;
    public static final int CANCUTILESESCOLARES = 12;
    public static final int CREATEDBY = 13;
    public static final int CREATIONDATE = 14;
    public static final int LASTUPDATEDBY = 15;
    public static final int LASTUPDATEDATE = 16;
    public static final int LASTUPDATELOGIN = 17;
    public static final int CALCCUOTASSERINF = 18;
    public static final int CALCCUOTASSERRET = 19;
    public static final int CALCCUOTASSERSTA = 20;
    public static final int CUOTAPATRONAL = 21;
    public static final int AJUSTEISN = 22;
    public static final int AJUSTELENTES = 23;

    /**This is the default constructor (do not remove)
     */
    public XxRcoPayjaustesBalanzaVORowImpl() {
    }

    /**Gets XxRcoPayAjustesBalanzaEO entity object.
     */
    public XxRcoPayAjustesBalanzaEOImpl getXxRcoPayAjustesBalanzaEO() {
        return (XxRcoPayAjustesBalanzaEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for NUMERO_MES using the alias name NumeroMes
     */
    public Number getNumeroMes() {
        return (Number) getAttributeInternal(NUMEROMES);
    }

    /**Sets <code>value</code> as attribute value for NUMERO_MES using the alias name NumeroMes
     */
    public void setNumeroMes(Number value) {
        setAttributeInternal(NUMEROMES, value);
    }

    /**Gets the attribute value for MES using the alias name Mes
     */
    public String getMes() {
        return (String) getAttributeInternal(MES);
    }

    /**Sets <code>value</code> as attribute value for MES using the alias name Mes
     */
    public void setMes(String value) {
        setAttributeInternal(MES, value);
    }

    /**Gets the attribute value for GRUPO_NOMINA using the alias name GrupoNomina
     */
    public String getGrupoNomina() {
        return (String) getAttributeInternal(GRUPONOMINA);
    }

    /**Sets <code>value</code> as attribute value for GRUPO_NOMINA using the alias name GrupoNomina
     */
    public void setGrupoNomina(String value) {
        setAttributeInternal(GRUPONOMINA, value);
    }

    /**Gets the attribute value for AJU_IMSS_DEDUCIBLE using the alias name AjuImssDeducible
     */
    public Number getAjuImssDeducible() {
        return (Number) getAttributeInternal(AJUIMSSDEDUCIBLE);
    }

    /**Sets <code>value</code> as attribute value for AJU_IMSS_DEDUCIBLE using the alias name AjuImssDeducible
     */
    public void setAjuImssDeducible(Number value) {
        setAttributeInternal(AJUIMSSDEDUCIBLE, value);
    }

    /**Gets the attribute value for AJU_IMSS_NO_DEDUCIBLE using the alias name AjuImssNoDeducible
     */
    public Number getAjuImssNoDeducible() {
        return (Number) getAttributeInternal(AJUIMSSNODEDUCIBLE);
    }

    /**Sets <code>value</code> as attribute value for AJU_IMSS_NO_DEDUCIBLE using the alias name AjuImssNoDeducible
     */
    public void setAjuImssNoDeducible(Number value) {
        setAttributeInternal(AJUIMSSNODEDUCIBLE, value);
    }

    /**Gets the attribute value for CANC_FA_PERIODO_ANTERIOR using the alias name CancFaPeriodoAnterior
     */
    public Number getCancFaPeriodoAnterior() {
        return (Number) getAttributeInternal(CANCFAPERIODOANTERIOR);
    }

    /**Sets <code>value</code> as attribute value for CANC_FA_PERIODO_ANTERIOR using the alias name CancFaPeriodoAnterior
     */
    public void setCancFaPeriodoAnterior(Number value) {
        setAttributeInternal(CANCFAPERIODOANTERIOR, value);
    }

    /**Gets the attribute value for CANC_FA using the alias name CancFa
     */
    public Number getCancFa() {
        return (Number) getAttributeInternal(CANCFA);
    }

    /**Sets <code>value</code> as attribute value for CANC_FA using the alias name CancFa
     */
    public void setCancFa(Number value) {
        setAttributeInternal(CANCFA, value);
    }

    /**Gets the attribute value for CANC_SYR using the alias name CancSyr
     */
    public Number getCancSyr() {
        return (Number) getAttributeInternal(CANCSYR);
    }

    /**Sets <code>value</code> as attribute value for CANC_SYR using the alias name CancSyr
     */
    public void setCancSyr(Number value) {
        setAttributeInternal(CANCSYR, value);
    }

    /**Gets the attribute value for CANC_PROV_PRIM_VAC using the alias name CancProvPrimVac
     */
    public Number getCancProvPrimVac() {
        return (Number) getAttributeInternal(CANCPROVPRIMVAC);
    }

    /**Sets <code>value</code> as attribute value for CANC_PROV_PRIM_VAC using the alias name CancProvPrimVac
     */
    public void setCancProvPrimVac(Number value) {
        setAttributeInternal(CANCPROVPRIMVAC, value);
    }

    /**Gets the attribute value for CANC_PROV_AGUINALDO using the alias name CancProvAguinaldo
     */
    public Number getCancProvAguinaldo() {
        return (Number) getAttributeInternal(CANCPROVAGUINALDO);
    }

    /**Sets <code>value</code> as attribute value for CANC_PROV_AGUINALDO using the alias name CancProvAguinaldo
     */
    public void setCancProvAguinaldo(Number value) {
        setAttributeInternal(CANCPROVAGUINALDO, value);
    }

    /**Gets the attribute value for CANC_UTILES_ESCOLARES using the alias name CancUtilesEscolares
     */
    public Number getCancUtilesEscolares() {
        return (Number) getAttributeInternal(CANCUTILESESCOLARES);
    }

    /**Sets <code>value</code> as attribute value for CANC_UTILES_ESCOLARES using the alias name CancUtilesEscolares
     */
    public void setCancUtilesEscolares(Number value) {
        setAttributeInternal(CANCUTILESESCOLARES, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ANIO:
            return getAnio();
        case NUMEROMES:
            return getNumeroMes();
        case MES:
            return getMes();
        case GRUPONOMINA:
            return getGrupoNomina();
        case AJUIMSSDEDUCIBLE:
            return getAjuImssDeducible();
        case AJUIMSSNODEDUCIBLE:
            return getAjuImssNoDeducible();
        case CANCFAPERIODOANTERIOR:
            return getCancFaPeriodoAnterior();
        case CANCFA:
            return getCancFa();
        case CANCSYR:
            return getCancSyr();
        case CANCPROVPRIMVAC:
            return getCancProvPrimVac();
        case CANCPROVAGUINALDO:
            return getCancProvAguinaldo();
        case CANCUTILESESCOLARES:
            return getCancUtilesEscolares();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CALCCUOTASSERINF:
            return getCalcCuotaSsErInf();
        case CALCCUOTASSERRET:
            return getCalcCuotaSsErRet();
        case CALCCUOTASSERSTA:
            return getCalcCuotaSsErSta();
        case CUOTAPATRONAL:
            return getCuotaPatronal();
        case AJUSTEISN:
            return getAjusteIsn();
        case AJUSTELENTES:
            return getAjusteLentes();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case NUMEROMES:
            setNumeroMes((Number)value);
            return;
        case MES:
            setMes((String)value);
            return;
        case GRUPONOMINA:
            setGrupoNomina((String)value);
            return;
        case AJUIMSSDEDUCIBLE:
            setAjuImssDeducible((Number)value);
            return;
        case AJUIMSSNODEDUCIBLE:
            setAjuImssNoDeducible((Number)value);
            return;
        case CANCFAPERIODOANTERIOR:
            setCancFaPeriodoAnterior((Number)value);
            return;
        case CANCFA:
            setCancFa((Number)value);
            return;
        case CANCSYR:
            setCancSyr((Number)value);
            return;
        case CANCPROVPRIMVAC:
            setCancProvPrimVac((Number)value);
            return;
        case CANCPROVAGUINALDO:
            setCancProvAguinaldo((Number)value);
            return;
        case CANCUTILESESCOLARES:
            setCancUtilesEscolares((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CALCCUOTASSERINF:
            setCalcCuotaSsErInf((Number)value);
            return;
        case CALCCUOTASSERRET:
            setCalcCuotaSsErRet((Number)value);
            return;
        case CALCCUOTASSERSTA:
            setCalcCuotaSsErSta((Number)value);
            return;
        case CUOTAPATRONAL:
            setCuotaPatronal((Number)value);
            return;
        case AJUSTEISN:
            setAjusteIsn((Number)value);
            return;
        case AJUSTELENTES:
            setAjusteLentes((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for CALC_CUOTA_SS_ER_INF using the alias name CalcCuotaSsErInf
     */
    public Number getCalcCuotaSsErInf() {
        return (Number) getAttributeInternal(CALCCUOTASSERINF);
    }

    /**Sets <code>value</code> as attribute value for CALC_CUOTA_SS_ER_INF using the alias name CalcCuotaSsErInf
     */
    public void setCalcCuotaSsErInf(Number value) {
        setAttributeInternal(CALCCUOTASSERINF, value);
    }

    /**Gets the attribute value for CALC_CUOTA_SS_ER_RET using the alias name CalcCuotaSsErRet
     */
    public Number getCalcCuotaSsErRet() {
        return (Number) getAttributeInternal(CALCCUOTASSERRET);
    }

    /**Sets <code>value</code> as attribute value for CALC_CUOTA_SS_ER_RET using the alias name CalcCuotaSsErRet
     */
    public void setCalcCuotaSsErRet(Number value) {
        setAttributeInternal(CALCCUOTASSERRET, value);
    }

    /**Gets the attribute value for CALC_CUOTA_SS_ER_STA using the alias name CalcCuotaSsErSta
     */
    public Number getCalcCuotaSsErSta() {
        return (Number) getAttributeInternal(CALCCUOTASSERSTA);
    }

    /**Sets <code>value</code> as attribute value for CALC_CUOTA_SS_ER_STA using the alias name CalcCuotaSsErSta
     */
    public void setCalcCuotaSsErSta(Number value) {
        setAttributeInternal(CALCCUOTASSERSTA, value);
    }

    /**Gets the attribute value for CUOTA_PATRONAL using the alias name CuotaPatronal
     */
    public Number getCuotaPatronal() {
        return (Number) getAttributeInternal(CUOTAPATRONAL);
    }

    /**Sets <code>value</code> as attribute value for CUOTA_PATRONAL using the alias name CuotaPatronal
     */
    public void setCuotaPatronal(Number value) {
        setAttributeInternal(CUOTAPATRONAL, value);
    }

    /**Gets the attribute value for AJUSTE_ISN using the alias name AjusteIsn
     */
    public Number getAjusteIsn() {
        return (Number) getAttributeInternal(AJUSTEISN);
    }

    /**Sets <code>value</code> as attribute value for AJUSTE_ISN using the alias name AjusteIsn
     */
    public void setAjusteIsn(Number value) {
        setAttributeInternal(AJUSTEISN, value);
    }

    /**Gets the attribute value for AJUSTE_LENTES using the alias name AjusteLentes
     */
    public Number getAjusteLentes() {
        return (Number) getAttributeInternal(AJUSTELENTES);
    }

    /**Sets <code>value</code> as attribute value for AJUSTE_LENTES using the alias name AjusteLentes
     */
    public void setAjusteLentes(Number value) {
        setAttributeInternal(AJUSTELENTES, value);
    }
}
