package xxrco.oracle.apps.pay.balanza.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxRcoPayAjuBzaProjEOImpl extends OAEntityImpl {
    public static final int ID = 0;
    public static final int ANIO = 1;
    public static final int NUMEROMES = 2;
    public static final int MES = 3;
    public static final int GRUPONOMINA = 4;
    public static final int PROYECTO = 5;
    public static final int REGISTROPATRONAL = 6;
    public static final int CALCCUOTASSERINF = 7;
    public static final int CALCCUOTASSERRET = 8;
    public static final int CALCCUOTASSERSTA = 9;
    public static final int D002IMSS = 10;
    public static final int D002IMSSSTA = 11;
    public static final int CREATEDBY = 12;
    public static final int CREATIONDATE = 13;
    public static final int LASTUPDATEDBY = 14;
    public static final int LASTUPDATEDATE = 15;
    public static final int LASTUPDATELOGIN = 16;
    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxRcoPayAjuBzaProjEOImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxrco.oracle.apps.pay.balanza.schema.server.XxRcoPayAjuBzaProjEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for Anio, using the alias name Anio
     */
    public Number getAnio() {
        return (Number)getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as the attribute value for Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for NumeroMes, using the alias name NumeroMes
     */
    public Number getNumeroMes() {
        return (Number)getAttributeInternal(NUMEROMES);
    }

    /**Sets <code>value</code> as the attribute value for NumeroMes
     */
    public void setNumeroMes(Number value) {
        setAttributeInternal(NUMEROMES, value);
    }

    /**Gets the attribute value for Mes, using the alias name Mes
     */
    public String getMes() {
        return (String)getAttributeInternal(MES);
    }

    /**Sets <code>value</code> as the attribute value for Mes
     */
    public void setMes(String value) {
        setAttributeInternal(MES, value);
    }

    /**Gets the attribute value for GrupoNomina, using the alias name GrupoNomina
     */
    public String getGrupoNomina() {
        return (String)getAttributeInternal(GRUPONOMINA);
    }

    /**Sets <code>value</code> as the attribute value for GrupoNomina
     */
    public void setGrupoNomina(String value) {
        setAttributeInternal(GRUPONOMINA, value);
    }

    /**Gets the attribute value for Proyecto, using the alias name Proyecto
     */
    public String getProyecto() {
        return (String)getAttributeInternal(PROYECTO);
    }

    /**Sets <code>value</code> as the attribute value for Proyecto
     */
    public void setProyecto(String value) {
        setAttributeInternal(PROYECTO, value);
    }

    /**Gets the attribute value for RegistroPatronal, using the alias name RegistroPatronal
     */
    public String getRegistroPatronal() {
        return (String)getAttributeInternal(REGISTROPATRONAL);
    }

    /**Sets <code>value</code> as the attribute value for RegistroPatronal
     */
    public void setRegistroPatronal(String value) {
        setAttributeInternal(REGISTROPATRONAL, value);
    }

    /**Gets the attribute value for CalcCuotaSsErInf, using the alias name CalcCuotaSsErInf
     */
    public Number getCalcCuotaSsErInf() {
        return (Number)getAttributeInternal(CALCCUOTASSERINF);
    }

    /**Sets <code>value</code> as the attribute value for CalcCuotaSsErInf
     */
    public void setCalcCuotaSsErInf(Number value) {
        setAttributeInternal(CALCCUOTASSERINF, value);
    }

    /**Gets the attribute value for CalcCuotaSsErRet, using the alias name CalcCuotaSsErRet
     */
    public Number getCalcCuotaSsErRet() {
        return (Number)getAttributeInternal(CALCCUOTASSERRET);
    }

    /**Sets <code>value</code> as the attribute value for CalcCuotaSsErRet
     */
    public void setCalcCuotaSsErRet(Number value) {
        setAttributeInternal(CALCCUOTASSERRET, value);
    }

    /**Gets the attribute value for CalcCuotaSsErSta, using the alias name CalcCuotaSsErSta
     */
    public Number getCalcCuotaSsErSta() {
        return (Number)getAttributeInternal(CALCCUOTASSERSTA);
    }

    /**Sets <code>value</code> as the attribute value for CalcCuotaSsErSta
     */
    public void setCalcCuotaSsErSta(Number value) {
        setAttributeInternal(CALCCUOTASSERSTA, value);
    }

    /**Gets the attribute value for D002imss, using the alias name D002imss
     */
    public Number getD002imss() {
        return (Number)getAttributeInternal(D002IMSS);
    }

    /**Sets <code>value</code> as the attribute value for D002imss
     */
    public void setD002imss(Number value) {
        setAttributeInternal(D002IMSS, value);
    }

    /**Gets the attribute value for D002imssSta, using the alias name D002imssSta
     */
    public Number getD002imssSta() {
        return (Number)getAttributeInternal(D002IMSSSTA);
    }

    /**Sets <code>value</code> as the attribute value for D002imssSta
     */
    public void setD002imssSta(Number value) {
        setAttributeInternal(D002IMSSSTA, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ANIO:
            return getAnio();
        case NUMEROMES:
            return getNumeroMes();
        case MES:
            return getMes();
        case GRUPONOMINA:
            return getGrupoNomina();
        case PROYECTO:
            return getProyecto();
        case REGISTROPATRONAL:
            return getRegistroPatronal();
        case CALCCUOTASSERINF:
            return getCalcCuotaSsErInf();
        case CALCCUOTASSERRET:
            return getCalcCuotaSsErRet();
        case CALCCUOTASSERSTA:
            return getCalcCuotaSsErSta();
        case D002IMSS:
            return getD002imss();
        case D002IMSSSTA:
            return getD002imssSta();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case NUMEROMES:
            setNumeroMes((Number)value);
            return;
        case MES:
            setMes((String)value);
            return;
        case GRUPONOMINA:
            setGrupoNomina((String)value);
            return;
        case PROYECTO:
            setProyecto((String)value);
            return;
        case REGISTROPATRONAL:
            setRegistroPatronal((String)value);
            return;
        case CALCCUOTASSERINF:
            setCalcCuotaSsErInf((Number)value);
            return;
        case CALCCUOTASSERRET:
            setCalcCuotaSsErRet((Number)value);
            return;
        case CALCCUOTASSERSTA:
            setCalcCuotaSsErSta((Number)value);
            return;
        case D002IMSS:
            setD002imss((Number)value);
            return;
        case D002IMSSSTA:
            setD002imssSta((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }
}
